# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths

networks:
    default: development
    # development:
        # gas_limit: max
        # gas_buffer: 1
        # gas_price: 0
        # max_fee: null
        # priority_fee: null
        # reverting_tx_gas_limit: max
        # default_contract_owner: true
    # - cmd: ganache-cli
    #   cmd_settings:
    #       port: 8545
    #       gas_limit: 6721975
    #       accounts: 10
    #       chain_id: 1337
    #       network_id: 1588949648
    #       evm_version: istanbul
    #       fork: null
    #       mnemonic: purse melody atom walk pelican buyer hire swamp expire left lady three
    #       block_time: 0
    #       default_balance: 100
    #       time: 2020-05-08T14:54:08+0000
    #       unlock: null
    

compiler:
    solc: 
      version: 0.8.6
      remappings:
        - "@openzeppelin=/home/loophe/brownie/juiceBox/node_modules/@openzeppelin"
        - "@chainlink=/home/loophe/brownie/juiceBox/node_modules/@chainlink"
        - "@paulrberg=/home/loophe/brownie/juiceBox/node_modules/@paulrberg"
        - "prb-math=/home/loophe/brownie/juiceBox/node_modules/prb-math"

wallets:
  from_key: ${PRIVATE_KEY}
  from_key1: ${PRIVATE_KEY1}


dotenv: .env